In [ ]:
import numpy as np

In [ ]:
list1 = [3,5,62,4,234,26,4,5]
type(list1)

list

In [ ]:
arr1 = np.array(list1)
arr1

array([  3,   5,  62,   4, 234,  26,   4,   5])

In [ ]:
type(arr1)

numpy.ndarray

In [ ]:
arr1.size

8

In [ ]:
z = np.zeros(15)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
z = np.ones(14)
z

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### 1-D array

In [ ]:
m = np.array([1,7,45,0])
m

array([ 1,  7, 45,  0])

### 2-D array

In [ ]:
n = np.array([[4,8,0],[9,0,3],[0,0,0],[8,7,6]])
n

array([[4, 8, 0],
       [9, 0, 3],
       [0, 0, 0],
       [8, 7, 6]])

In [ ]:
n.shape

(4, 3)

In [ ]:
n.ndim

2

In [ ]:
n = n.reshape(3,2,2)
n

array([[[4, 8],
        [0, 9]],

       [[0, 3],
        [0, 0]],

       [[0, 8],
        [7, 6]]])

In [ ]:
n.ndim

3

In [ ]:
n.shape

(3, 2, 2)

In [ ]:
n = n.reshape(3,4)
n

array([[4, 8, 0, 9],
       [0, 3, 0, 0],
       [0, 8, 7, 6]])

# INDEXING

### 1-D Array

In [ ]:
arr1 = np.array([3,5,62,4,234,26,4,5])
arr1

array([  3,   5,  62,   4, 234,  26,   4,   5])

In [ ]:
arr1[6]

4

### 2-D Array

In [ ]:
n = np.array([[4,8,0],[9,0,3],[0,0,0],[8,7,6]])
n

array([[4, 8, 0],
       [9, 0, 3],
       [0, 0, 0],
       [8, 7, 6]])

In [ ]:
n[1,0]

9

In [ ]:
n[1][0]

9

In [ ]:
#linspace
n = np.linspace(0,10,5)
n

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
#identity matrix
x = np.eye(5)
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
x.shape

(5, 5)

In [ ]:
np.random.randint(1,10,20)

array([1, 6, 8, 6, 8, 4, 8, 9, 1, 4, 1, 9, 1, 6, 5, 2, 6, 1, 3, 9])

In [ ]:
y = np.random.rand(5,4)
y

array([[0.9653132 , 0.090574  , 0.45412811, 0.90933922],
       [0.05921434, 0.11159908, 0.0095478 , 0.61883228],
       [0.21820423, 0.20446685, 0.44274485, 0.74455575],
       [0.46335181, 0.16243941, 0.63393227, 0.59036227],
       [0.00428877, 0.44270916, 0.26385035, 0.69101608]])

In [ ]:
y.shape

(5, 4)

In [ ]:
y.max()

0.9653132043477626

In [ ]:
y.argmax()

0

In [ ]:
#arange
x = np.arange(0,11,2) # Here 2=hop gap bw consecutive elements
x

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
n = np.array([[4,8,0],[9,0,3],[0,0,0],[8,7,6]])
n

array([[4, 8, 0],
       [9, 0, 3],
       [0, 0, 0],
       [8, 7, 6]])

In [ ]:
#Slicing
n[0:1, 0:2] #In slicing : array[start:end+1]

array([[4, 8]])

In [ ]:
n[2:4, 1:3]

array([[0, 0],
       [7, 6]])

In [ ]:
n[2:4][1:3] #spot the difference this command and previous command

array([[8, 7, 6]])

In [ ]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 

In [ ]:
a1 = np.arange(2,35,5)
a2 = np.arange(4,69,10)

In [ ]:
print(a1,a2)

[ 2  7 12 17 22 27 32] [ 4 14 24 34 44 54 64]


In [ ]:
c = a1+a2
c

array([ 6, 21, 36, 51, 66, 81, 96])

In [ ]:
np.sqrt(c)

array([2.44948974, 4.58257569, 6.        , 7.14142843, 8.1240384 ,
       9.        , 9.79795897])

In [ ]:
np.cos(c)

array([ 0.96017029, -0.54772926, -0.12796369,  0.7421542 , -0.99964746,
        0.77668598, -0.18043045])

In [ ]:
x = a1.copy()
x

array([ 2,  7, 12, 17, 22, 27, 32])

In [ ]:
z = x.view()
z

array([ 2,  7, 12, 17, 22, 27, 32])

In [ ]:
x[0] =99
x

array([99,  7, 12, 17, 22, 27, 32])

In [ ]:
z #Notice that any change in the main array 'x' causes changes in its view also (i.e. z)

array([99,  7, 12, 17, 22, 27, 32])

In [ ]:
z[0] = 22 #Therfore, any changes in view is also reflected in the original matrix.
x

array([22,  7, 12, 17, 22, 27, 32])